#!/bin/bash

error_handler () {
    errcode=$?
    echo "Got error code $errorcode"
    echo "Last command executed was"
    echo -e "\t$BASH_COMMAND"
    echo "on line ${BASH_LINENO[0]}"
    exit $errcode
}
trap error_handler ERR

PROJECTS_ZIP="/tmp/package.zip"

SCRIPT=$(readlink -f $0)
SCRIPTPATH=$(dirname $SCRIPT)

WORKING=$(mktemp -d)

echo "Working on ${WORKING}"

trap "rm -rf ${WORKING}" EXIT

PROJECT_HOME="${WORKING}/project"
mkdir "${PROJECT_HOME}"

unzip "${PROJECTS_ZIP}" -d "${PROJECT_HOME}"

#5.3
(cd "${PROJECT_HOME}/python/wwa_app_example" && find wwa_app_example -iname "*.py" -exec pylint {} \;)
#tests fail, so we unset the trap
trap - ERR
(cd "${PROJECT_HOME}/python/wwa_app_example" && python3 -m unittest discover -v -s tests -p \*.py)
#now set the trap back
trap error_handler ERR
(cd "${PROJECT_HOME}/python/wwa_app_example" && python3 -m setup sdist)
(cd "${PROJECT_HOME}/python/wwa_app_example" && python3 -m setup bdist_wheel)
(cd "${PROJECT_HOME}/python/wwa_app_example" && python3 -m virtualenv -p python3 env && source env/bin/activate && python3 -m setup install && wwa_devops && deactivate)
PYTHON_APP_VERSION=$(cd "${PROJECT_HOME}/python/wwa_app_example" && cat version.txt)

